# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.FloatField(default=0),
        ),
    ]
