# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_time_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.IntegerField(default=10)),
                ('logged_at', models.DateTimeField(default=datetime.datetime.now)),
                ('happened_at', models.DateTimeField(default=datetime.datetime.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
            ],
        ),
    ]
