# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timetrack2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr', to='core.Task')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='core.Task')),
            ],
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='child',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
